### ISSUE TITLE
License

### ISSUE THREAD

**Issue by johanneswilm** [ptgolden/edtf-js#1]
Hey @ptgolden,
is there an open source license associated with this?

**Comment by ptgolden** [comment]
I added an AGPLv3 license.

I can't vouch for this code at all- it was one of the first pieces of code I ever wrote from scratch, and I can't vouch for its completeness or correctness. I would highly recommend using [inukshuk/edtf.js](https://github.com/inukshuk/edtf.js) rather than this. That repository uses a proper parser based off the the grammar in the standard, which is much better than whatever ad-hoc regex-wrangling approach I came up with.

**Comment by johanneswilm** [comment]
Hey, thank you for adding that license! I have been using that other library you link to for our LGPL licensed bibtex-csl conversion library [1], but it has issues (look at the issues I filed) and I'm not sure they can be fixed in the near future (year or so). Also, it's trying to do a bunch of things we don't really need (create a new type of Data object that cannot be transpiled to pre-ES6 code, EDTF Level 2+ which are not supported in the formats we are working with).

The license is unfortunately another pain point -- Out license is LGPL, and I am not a copyright lawyer but it seems that that may not actually be possible if one includes AGPL code. Now you have the same license, so the problem is the same with this library.

Maybe I just need to write another simple parser library just for EDTF level 0 and level 1 and license that LGPL or something like that. Anyway, thanks for the prompt response!

[1] https://github.com/fiduswriter/biblatex-csl-converter

**Comment by johanneswilm** [comment]
Should anyone else come here: With the additional of the AGPL license here, I wrote an LGPL licensed parser from scratch. It only does those parts of level 0 and 1 that are supported by biblatex and CSL. The parser is even more basic than the one here, and I hope it can be replaced fairly soon. It does survive all our test cases. See https://github.com/fiduswriter/biblatex-csl-converter/commit/2f06b293b92e44668b3e207bbebaf23810fe8be3

**Comment by ptgolden** [comment]
Thanks, Johannes, and good luck to you! Fidus Writer looks like a great project.
